### ISSUE TITLE
Could you specify which code mode is used?

### ISSUE THREAD

**Issue by prob1995** [IgorTitov/LabVIEW-Advanced-Encryption-Standard#1]
This code is really useful!
I am trying to use other language (such as python) to handshake with this library.
However, I can't found any code mode information in this code (ex. ECB, CBC, CTR...).
Could you specify which code mode you are using in this code?

**Comment by IgorTitov** [comment]
Thank you, I'm not sure if it was you whom I replied in email. Anyway, this implementation is in CTR mode.

**Comment by prob1995** [comment]
Yes, it's me in email! Thanks for the answer. I will try with CTR mode. Thanks!
